version: '3'
services:
  app:
    container_name: app
    build:
      context: ./php
    working_dir: /var/www
    volumes:
      - ../traveler-l6:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
  webserver:
    image: nginx:alpine
    ports:
      - "8580:80"
    volumes:
      - ../traveler-l6:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8581:80"
    environment:
      MYSQL_USERNAME: laravel
      MYSQL_ROOT_PASSWORD: laravel
      PMA_HOST: db
    networks:
      - laravel-network

#Docker Networks
networks:
  laravel-network:
    driver: bridge